# Applications to backup
apps: []
# - name: example
#   backupSchedule: "0 2 * * *"
#   cleanupSchedule: "0 5 * * *"
#   checkSchedule: "0 12 * * *"
#   unlockSchedule: "0 15 * * *"
#   keep:
#     last: 5
#     within: 1m
#   resticCredentials:
#     RESTIC_REPOSITORY: s3:fra1.digitaloceanspaces.com/example/example
#     RESTIC_PASSWORD: CHANGEME
#     AWS_ACCESS_KEY_ID: CHANGEME
#     AWS_SECRET_ACCESS_KEY: CHANGEME
#   postgresCredentials:
#     PGDATABASE: example_db
#     PGUSER: example_user
#     PGPASSWORD: example_password
#     PGHOST: pg.example.com
#   timeouts:
#     cleanup: 1000
#     create: 7000

# Enables and configures a CloudSQL proxy instance.
# Use it if you do not have a private-network-connected PG db instance.
proxy:
  affinity: {}
  credentialsJson: ""
  enabled: false
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: 1.16
    pullPolicy: IfNotPresent
  instances: ""
  nodeSelector: {}
  replicaCount: 1
  resources: {}
  secretName: cloudsql-proxy-credentials
  service:
    type: ClusterIP
    port: 5432
  tolerations: []

restic:
  affinity: {}
  image:
    repository: quay.io/evl.ms/pgrestic
    tag: 0.9.6-r0-9.6.17-alpine
    pullPolicy: IfNotPresent
  nodeSelector: {}
  replicaCount: 1
  resources: {}
  tolerations: []
