{{- range .Values.apps }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: {{ .name }}-backup-cleanup
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .name }}-cloudsql-backup-cleanup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}-backup-cleanup
        app.kubernetes.io/instance: {{ $.Release.Name }}
      name: cloudsql-backup-cleanup
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 3
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .name }}-backup-cleanup
            app.kubernetes.io/instance: {{ $.Release.Name }}
        spec:
          containers:
          - name: restic
            image: "{{ $.Values.restic.image.repository }}:{{ $.Values.restic.image.tag }}"
            imagePullPolicy: {{ $.Values.restic.image.pullPolicy }}
            command:
            - /usr/bin/restic
            - forget
            - --prune
            - --keep-last=2
            - --keep-daily=7
            - --keep-weekly=4
            - --keep-monthly=3
            envFrom:
            - secretRef:
                name: {{ .name }}-restic-credentials
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
  schedule: {{ .cleanup_schedule }}
  successfulJobsHistoryLimit: 3
  suspend: false
{{ end }}
