{{- range .Values.apps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .name }}-backup-create
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .name }}-backup-command
data:
  backup-command.sh: |
    #!/bin/sh
    /usr/local/bin/pg_dump --format=c | /usr/bin/restic backup --host={{ .name }}-backup --stdin --stdin-filename="${PGDATABASE}-$(date +%F_%H:%M:%S).dump"
{{ end }}
