{{- if and .Values.proxy.enabled .Values.proxy.credentials_json }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: backup-create
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .Values.proxy.secretName }}
data:
  credentials.json: {{ .Values.proxy.credentialsJson | b64enc }}
{{- end }}
